# Site
repository: Essoz/Essoz.github.io
favicon: images/favicon.ico #Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yuxuan Jiang (Matt)
title: B.E. Junior student at ZJU-UIUC in Computer Engineering
email: yuxuanj9@illinois.edu
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: Comming Soon
website_title: Blog #(Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  essoz
stackoverflow_username: "12889336"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: yuxuan-jiang-a2b11921a
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg #Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I am Yuxuan Jiang (Matt), a junior student in CompE at ZJU-UIUC institute. Currently my research interest is in distributed systems, high performance, etc.

content:
  - title: Education
    layout: list
    content:
      - layout: top
        # title: [ZJU-UIUC Institute](https://zjui.intl.zju.edu.cn/en)
        title: ZJU-UIUC Institute
        sub_title: B.E. in Computer Engineering at both University of Illinois at Urbana-Champaign and Zhejiang University
        caption: 2019 - 2023
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          The program is offered by the partnership between Zhejiang University and the University of Illinois at Urbana-Champaign (UIUC). All non-political curriculums and resources are imported from UIUC. Core courses are present by UIUC professors and lectures.
      - layout: top
        title: University of Illinois at Urbana-Champaign
        sub_title: Exchange at UIUC
        caption: 2022 - 2023
        description: |
          The exchange program is offered for ZJU-UIUC students to better explore possibilities in their future careers and to enjoy a much wider range of academic resources.
  
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: DepFast
        sub_title: Fail-slow fault tolerance needs programming support
        caption: 2021
        link: https://dl.acm.org/doi/10.1145/3458336.3465299 #Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Previously published workshop paper
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          The research is ongoing.
        description: | # this will include new lines to allow paragraphs
          My work mainly focused on testing fault-slow tolerance of PolarDB-for-PostgreSQL (PolarDB for short) during 2021 "UIUC Undergraduate Summer Research" program. Future work to be added.
      
      - layout: top
        title: BSP-based Data Replication Processing in Distributed Databases
        caption: 2021
        quote: >
          The research is ongoing.
        description: | # this will include new lines to allow paragraphs
          This is a SRTP project that explores applications of BSP algorithms in distributed databases, guided by Klaus-Dieter Schewe.


        
  - title: Awards
    layout: list
    content:
      - layout: top
        title: Provincial Gold Award
        sub_title: Internet+ Innovation and Entrepreneurship Competition (Zhejiang Province)
        caption: 2021
        description: |
          "Distributed High Performance Computing" (D-HPC for short).  
          The project aims to provide highly-available and low-latency computational services in the city by deploying a distributed supercomputer network. 
          D-HPC supports the construction of "Smart City" and "Industrial Network". It also make user experience better in terms of cloud-based apps, such as cloud-gaming.
          It also values data-uniqueness and the user's sovereignty of data by integrating the blockchain technology into the network. We also aim to accelerate the age of Web3.0. 
      - layout: top
        title: First Prize
        sub_title: International Concrete Dragon Boat Competition
        caption: 2020
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Designer of the control system.
      - layout: top
        title: Second National Prize 
        sub_title: ChangFeng National Contest in Big Data Analysis and Mining
        caption: 2021
        # description: |
        #   haha         

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
